service: ts-sequelize-serverless-boilerplate

configValidationMode: error

frameworkVersion: "3"

plugins:
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

custom:
  params:
    externalApiBaseUrl: /${self:service}/${sls:stage}/EXTERNAL_API_BASE_URL
    externalApiKey: /${self:service}/${sls:stage}/EXTERNAL_API_KEY
  names:
    functions:
      sayHello: ${self:service}-${sls:stage}-sayHello
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: node16
    define: { "require.resolve": undefined }
    platform: node
    concurrency: 10

provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024

  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
    EXTERNAL_API_BASE_URL: ${ssm:${self:custom.params.externalApiBaseUrl}}
    EXTERNAL_API_KEY: ${ssm:${self:custom.params.externalApiKey}}

functions:
  sayHello:
    name: ${self:custom.names.functions.sayHello}
    timeout: 30
    handler: event.sayHello
    events:
      - http:
          path: /hello
          method: post
          cors: true
