name: Deploy Serverless Framework (AWS) Dev
on:
  push:
    branches:
      - develop
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}

      - name: Create env file
        run: | # cp sample.env.yml env.yml
          cat > env.yml << EOF
          ${{ secrets.ENV }}
          EOF

      - name: Install NPM dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Deploy Lambda functions
        run: sls deploy --region ${{ secrets.AWS_REGION }} --stage "development"